name: Expo Doctor (expo)

on:
  push:
    branches:
      - main
      - master
    paths:
      - "package.json"
      - "pnpm-lock.yaml"
  pull_request:
    paths:
      - "package.json"
      - "pnpm-lock.yaml"

jobs:
  doctor:
    name: Expo Doctor (expo)
    runs-on: ubuntu-latest

    steps:
      - name : 📦 Checkout project repo
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: 📦 Install Project Dependencies
        run: pnpm install --frozen-lockfile

      - name: 🚑 Run Doctor Checks
        run: rm -rf ios android && pnpm run doctor ## apprently the new update of expo will break if you already have ios and android folders in your project as they will show up a eas warning