name: Validate PR

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  type-check:
    uses: ./.github/workflows/type-check.yml

  lint:
    uses: ./.github/workflows/lint-ts.yml

  doctor:
    uses: ./.github/workflows/expo-doctor.yml

  test:
    uses: ./.github/workflows/test.yml